#!/usr/bin/env python3
"""Reproducible local font generation: fonttools[woff]==4.66.0. Keeps all cmap characters."""
from pathlib import Path
import json
from fontTools.ttLib import TTFont
from fontTools import subset
root = Path(__file__).resolve().parents[1]
folder = root / 'src/assets/fonts'
common = set(range(0x250)) | set(range(0x1e00,0x1f00)) | set(range(0x2000,0x2070)) | set(range(0x20a0,0x2200)) | {0x2212,0xfeff,0xfffd}
def ranges(points):
    runs=[]
    for point in sorted(points):
        if runs and point==runs[-1][1]+1: runs[-1][1]=point
        else: runs.append([point,point])
    return ','.join(f'U+{a:X}' + (f'-{b:X}' if a!=b else '') for a,b in runs)
css=[]
manifest=[]
for base, family in [('cinzel-variable','Cinzel'),('cormorant-garamond-variable','Cormorant Garamond')]:
    original=TTFont(folder / f'{base}.ttf')
    cmap=original.getBestCmap()
    axes=[(axis.axisTag,axis.minValue,axis.defaultValue,axis.maxValue) for axis in original['fvar'].axes]
    covered=set()
    for name,points in [('latin',set(cmap)&common),('extended',set(cmap)-common)]:
        if not points: continue
        font=TTFont(folder/f'{base}.ttf', recalcTimestamp=False)
        options=subset.Options()
        options.layout_features=['*']
        options.name_IDs=['*']
        options.name_legacy=True
        options.name_languages=['*']
        options.glyph_names=True
        options.recalc_timestamp=False
        sub=subset.Subsetter(options=options);sub.populate(unicodes=points);sub.subset(font)
        font.flavor='woff2'
        destination=folder/f'{base}-{name}.woff2'
        font.save(destination)
        check=TTFont(destination)
        assert set(check.getBestCmap())==points
        assert [(a.axisTag,a.minValue,a.defaultValue,a.maxValue) for a in check['fvar'].axes]==axes
        assert not covered&points
        for code in points:
            assert original['hmtx'][cmap[code]]==check['hmtx'][check.getBestCmap()[code]]
        covered|=points
        css.append(f"@font-face {{\n\tfont-family: '{family}';\n\tsrc: url('../assets/fonts/{destination.name}') format('woff2');\n\tfont-weight: {'400 900' if family=='Cinzel' else '300 700'};\n\tfont-style: normal;\n\tfont-display: swap;\n\tunicode-range: {ranges(points)};\n}}\n")
        manifest.append({'font':destination.name,'characters':len(points),'bytes':destination.stat().st_size,'unicodeRange':ranges(points)})
    assert covered==set(cmap), f'{family}: missing original characters'
(root/'src/styles/fonts.css').write_text('/* Generated by scripts/subset-fonts.py; SIL OFL 1.1 licenses in public/licenses/. */\n'+'\n'.join(css))
print(json.dumps(manifest,indent=2))
